apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virt-lab-demo
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/cmalafisredhat/virt-lab-gitops.git
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

