apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: prod-vm-db1
  namespace: prod
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: prod-vm-db1
    spec:
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 1Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: prod-vm-db1-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-vm-db1-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-external-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 10Gi

