apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: lab-vm1
  namespace: lab
spec:
  running: true
  dataVolumeTemplates:
    - metadata:
        name: lab-vm1-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 35Gi
          storageClassName: ocs-external-storagecluster-ceph-rbd
  template:
    metadata:
      labels:
        kubevirt.io/domain: lab-vm1
    spec:
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
      volumes:
        - name: rootdisk
          dataVolume:
            name: lab-vm1-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: cloud-user
              password: redhat
              chpasswd: { expire: False }
              ssh_pwauth: True

